### ISSUE TITLE
Support gifwit libraries?

### ISSUE THREAD

**Issue by Ruxton** [martymcguire/kapowski#1]
I've been curating gifs in the [gifwit](https://gifwit.com/) library format using https://github.com/Ruxton/gifwiddit . It'd be nice to be able to load that library.

**Comment by martymcguire** [comment]
Thanks @Ruxton! I tried to make Kapowski simple and single-use, so I am a little hesitant to add multiple backends that might complicate the UI.

That said, Kapowski was also my first attempt at a "minimum viable" micropub client. So it may be possible to get a quick win by forking the project on Glitch and swapping out the backend! https://glitch.com/edit/#!/garrulous-smile

**Comment by martymcguire** [comment]
revisiting this several months later. upon the acquisition of giphy by Facebook I decided to switch the main backend to gfycat. To my recollection this took a couple of hours, including time to get familiar with gfycat's API offerings.

I think it makes sense to keep Kapowski simple and encourage forks for different GIF libraries for now!
